### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by bradlarsen** [praetorian-inc/noseyparker#121]
It would be useful if Nosey Parker would build and run on Windows. The releases should also include prebuilt Windows binary releases.

I've not tried building on Windows. It should work in theory, but:
- The cmake-related bits for Vectorscan and zlib might cause trouble
- There may be some platform-specific code in Nosey Parker

**Comment by bradlarsen** [comment]
I haven't tried on a native Windows machine, but tried a [cross](https://github.com/cross-rs/cross) build from macOS:
```
$ cargo install -f cross
$ export TARGET="x86_64-pc-windows-gnu" ; rustup target add "$TARGET" ; export RUSTFLAGS="-C target-feature=+crt-static"
$ cross build --target "$TARGET" --release
```

This fails with the following error:
```
error: failed to run custom build command for `vectorscan-sys v0.0.0 (/project/crates/vectorscan-sys)`

Caused by:
  process didn't exit successfully: `/target/release/build/vectorscan-sys-887de5b3182866e7/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=stdc++
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_gnu = None
  TARGET_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-gnu = None
  CMAKE_GENERATOR_x86_64_pc_windows_gnu = None
  TARGET_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-gnu = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_gnu = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-gnu = None
  CMAKE_x86_64_pc_windows_gnu = None
  TARGET_CMAKE = None
  CMAKE = None
  running: cd "/target/x86_64-pc-windows-gnu/release/build/vectorscan-sys-9325e5473307dfb1/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/project/crates/vectorscan-sys/vectorscan" "-DCMAKE_INSTALL_INCLUDEDIR=/target/x86_64-pc-windows-gnu/release/build/vectorscan-sys-9325e5473307dfb1/out/include" "-DFAT_RUNTIME=ON" "-DBUILD_AVX512=OFF" "-DBUILD_EXAMPLES=OFF" "-DBUILD_BENCHMARKS=OFF" "-DBUILD_UNITTESTS=OFF" "-DBUILD_DOCS=OFF" "-DBUILD_TOOLS=OFF" "-DCMAKE_SYSTEM_NAME=Windows" "-DCMAKE_SYSTEM_PROCESSOR=AMD64" "-DCMAKE_INSTALL_PREFIX=/target/x86_64-pc-windows-gnu/release/build/vectorscan-sys-9325e5473307dfb1/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_C_COMPILER=/usr/bin/x86_64-w64-mingw32-gcc-posix" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/x86_64-w64-mingw32-g++-posix" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/x86_64-w64-mingw32-gcc-posix" "-DCMAKE_BUILD_TYPE=Release"
  -- The C compiler identification is GNU 7.3.0
  -- The CXX compiler identification is GNU 7.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc-posix - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/x86_64-w64-mingw32-g++-posix - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Performing Test ARCH_X86_64
  -- Performing Test ARCH_X86_64 - Success
  -- Performing Test ARCH_IA32
  -- Performing Test ARCH_IA32 - Failed
  -- Performing Test ARCH_AARCH64
  -- Performing Test ARCH_AARCH64 - Failed
  -- Performing Test ARCH_ARM32
  -- Performing Test ARCH_ARM32 - Failed
  -- Performing Test ARCH_PPC64EL
  -- Performing Test ARCH_PPC64EL - Failed
  -- Build type RELEASE
  -- using release build
  -- Boost version: 1.83.0
  -- Build date: 2024-01-29
  -- Building static libraries
  -- gcc version 7.3.0
  -- gcc will tune for broadwell, broadwell
  -- ARCH_C_FLAGS   : -msse4.2
  -- ARCH_CXX_FLAGS : -msse4.2
  -- g++ version 7.3.0
  -- Configuring incomplete, errors occurred!
  See also "/target/x86_64-pc-windows-gnu/release/build/vectorscan-sys-9325e5473307dfb1/out/build/CMakeFiles/CMakeOutput.log".
  See also "/target/x86_64-pc-windows-gnu/release/build/vectorscan-sys-9325e5473307dfb1/out/build/CMakeFiles/CMakeError.log".

  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Error at CMakeLists.txt:264 (message):
    A minimum of g++ 9 is required for C++17 support


  thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by munntjlx** [comment]
Looks like you need to target a HIGHER version of GCC and g++ but I suspect you already know that!

**Comment by munntjlx** [comment]
Have you looked at mingw? Its a different compiler for windows.

**Comment by bradlarsen** [comment]
Thanks @munntjlx, all reasonable suggestions. I haven't spent more than cursory time looking into this. The results from above were trying to use the `cross` tool for cross-platform building using Docker containers, without any kind of environment customization.

**Comment by bradlarsen** [comment]
Note for posterity: apparently the native Linux release binaries work without trouble on Windows using WSL1.

WSL2 is reported as being problematic for requiring nested virtualization support or something else.

**Comment by bradlarsen** [comment]
Note: the Vectorscan C++ code doesn't officially support windows and doesn't have any plans to do so: https://github.com/VectorCamp/vectorscan/discussions/314

It might be possible with some build system patches to get that building on Windows.

Getting [`vectorscan-rs`](https://github.com/bradlarsen/vectorscan-rs) building on Windows would be a necessary step for Nosey Parker to build on Windows.

**Comment by daddycocoaman** [comment]
@bradlarsen Vectorscan is supposed to be compatible with Hyperscan 5.4 ABI and basically a drop-in replacement, so would it be possible to have platform-dependent builds where Windows uses Hyperscan and other platforms use Vectorscan? Modifying vectorscan-sys and vectorscan-rs-sys to just use hyperscan instead as a `feature` or something (sorry, new to Rust terms) might work out.

**Comment by bradlarsen** [comment]
@daddycocoaman Yes, maybe possible. I ended up writing custom Rust bindings to Vectorscan (https://github.com/bradlarsen/vectorscan-rs) that would need to be updated with some plumbing-type work to link against Hyperscan instead of Vectorscan.

I'm not planning that work right away, and at first thought I'd prefer doing the work on the Vectorscan C++ codebase to get it building on Windows. I looked at that briefly several months ago, and it seemed like it might be just a bunch of build system scripts, CMake stuff, and maybe some `#define`s that would need adjustment to get it building on Windows.

**Comment by aredspyinthebase** [comment]
Tried this on a windows box with MinGW and was able to build all the dependent cargo packages including the `vectorscan-rs` binding package.

First platform dependent error:

```
error[E0432]: unresolved import `rlimit::Resource`
  --> crates\noseyparker-cli\src\main.rs:65:9
   |
65 |     use rlimit::Resource;
   |         ^^^^^^^^^^^^^^^^ no `Resource` in the root
   |
help: consider importing this struct instead
   |
65 |     use gix::diff::blob::platform::Resource;
   |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0432`.
error: could not compile `noseyparker-cli` (bin "noseyparker-cli") due to 1 previous error
```

Not sure which other platform dependent packages noseyparker uses, but will check if I can reach the same result with cross build.

**Comment by bradlarsen** [comment]
@aredspyinthebase Oh, that's really good to know! It might be easier to build on Windows than I thought (though maybe mingw will be required there).

The `rlimit::Resource` bit in `crates/noseyparker-cli/src/main.rs` is Unix-specific, and probably just needs to be put behind something like `#[cfg(not(target_os = "windows"))]`.

**Comment by Coruscant11** [comment]
Hello @bradlarsen!
I am currently pushing to look at converting the secrets scanner used in my company (at very large scale, we are talking about 80k repositories) to noseyparker, and my current blocking point is Windows.

I was wondering if I could help you on the windows compilation of vectorscan.

Do you maybe have a list of the remaining task, that I could explore on my side maybe if it can help you? :)
What are the blocking point currently?

I would be really happy to help you on that if needed!

Thanks!

**Comment by munntjlx** [comment]
I believe the main problem is the lack of support for various vectorscan makefiles in windows. I would suggest using wsl2 or wsl1 or a linux container in windows to help with this effort. There is no huge demand for windows since containers and other platforms seem to compile this fine.  I don't speak for the noseyparker people, just my opinion.

________________________________________

**Comment by bradlarsen** [comment]
@aredspyinthebase did you have to set up anything specially in the environment to build on Windows?? I'm trying to replicate this now but without special environment settings have run into build failures in `vectorscan-rs`.

**Comment by bradlarsen** [comment]
@daddycocoaman were you able to build vectorscan-rs with MSVC??

**Comment by Coruscant11** [comment]
Thanks for your answer @bradlarsen, I will start to look at it tomorrow on my side 💪

I will update my progress here :)

**Comment by aredspyinthebase** [comment]
@bradlarsen If building in a windows shell, `$env:PATH += ";C:\msys64\mingw64\bin;C:\msys64\usr\bin"` is required so that cargo can access the mingw/msys2 binaries. Otherwise, bash on msys2 with MinGW should work out of box.

Not too familiar with the GitHub Actions, but I think you need to specify MinGW as the msystem with an msys2 workflow: https://www.msys2.org/docs/ci/

For the specific `vectorscan-rs` error, its looking for the `patch` binary which exists in msys2 but not mingw, hence why you need both bin paths on PATH:

```
error: failed to run custom build command for `vectorscan-rs-sys v0.0.5`

Caused by:
  process didn't exit successfully: `C:\Users\localuser\Documents\noseyparker\target\debug\build\vectorscan-rs-sys-d137caacf64b0560\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=vectorscan.patch
  cargo:rustc-link-lib=stdc++

  --- stderr
  Tarball extracted to C:\Users\localuser\Documents\noseyparker\target\x86_64-pc-windows-gnu\debug\build\vectorscan-rs-sys-fcbb7825047946b7\out
  Vectorscan source directory is at C:\Users\localuser\Documents\noseyparker\target\x86_64-pc-windows-gnu\debug\build\vectorscan-rs-sys-fcbb7825047946b7\out\vectorscan-vectorscan-5.4.11

  thread 'main' panicked at C:\Users\localuser\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\vectorscan-rs-sys-0.0.5\build.rs:84:14:
  Failed to apply patchfile: Error { kind: NotFound, message: "program not found" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by daddycocoaman** [comment]
@bradlarsen I was able to get to the same `rlimit::Resource` issue @aredspyinthebase reached when I first tried with msvc but hadn't looked it at since. I tried against yesterday and I was getting issues with `pkg-config` not being found but my dev environment has changed so I might be missing something. 

Most of the issues, as mentioned, is just PATH stuff like `patch`. The `patch` binary can be found in the Git installation folder so those are easy fixes. Also had an issue with Boost headers so had to download those specifically. I am running the build is Developer PowerShell.

```
PS C:\Users\LeronGray\dev\vectorscan-rs> $env:Path += ';C:\Program Files\Git\usr\bin'
PS C:\Users\LeronGray\dev\vectorscan-rs> cargo build
   Compiling vectorscan-rs-sys v0.0.5 (C:\Users\LeronGray\dev\vectorscan-rs\vectorscan-rs-sys)
error: failed to run custom build command for `vectorscan-rs-sys v0.0.5 (C:\Users\LeronGray\dev\vectorscan-rs\vectorscan-rs-sys)`

Caused by:
  process didn't exit successfully: `C:\Users\LeronGray\dev\vectorscan-rs\target\debug\build\vectorscan-rs-sys-6a685ff83347d9f8\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=vectorscan.patch
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\LeronGray\\dev\\vectorscan-rs\\target\\debug\\build\\vectorscan-rs-sys-d4b542f12fe7422c\\out\\vectorscan-vectorscan-5.4.11" "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DCMAKE_INSTALL_INCLUDEDIR=C:\\Users\\LeronGray\\dev\\vectorscan-rs\\target\\debug\\build\\vectorscan-rs-sys-d4b542f12fe7422c\\out\\include" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DBUILD_SHARED_LIBS=OFF" "-DBUILD_STATIC_LIBS=ON" "-DFAT_RUNTIME=OFF" "-DWARNINGS_AS_ERRORS=OFF" "-DBUILD_EXAMPLES=OFF" "-DBUILD_BENCHMARKS=OFF" "-DBUILD_DOC=OFF" "-DBUILD_TOOLS=OFF" "-DBOOST_ROOT=C:\\Users\\LeronGray\\dev\\boost_1_88_0" "-DBUILD_UNIT=OFF" "-DUSE_CPU_NAIVE=OFF" "-DBUILD_AVX2=OFF" "-DBUILD_AVX512=OFF" "-DBUILD_AVX512VBMI=OFF" "-DBUILD_SVE=OFF" "-DBUILD_SVE2=OFF" "-DBUILD_SVE2_BITPERM=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\LeronGray\\dev\\vectorscan-rs\\target\\debug\\build\\vectorscan-rs-sys-d4b542f12fe7422c\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"
  -- Build date: 2025-05-15
  -- Boost version: 1.88.0
  -- Configuring incomplete, errors occurred!

  --- stderr
  Tarball extracted to C:\Users\LeronGray\dev\vectorscan-rs\target\debug\build\vectorscan-rs-sys-d4b542f12fe7422c\out
  Vectorscan source directory is at C:\Users\LeronGray\dev\vectorscan-rs\target\debug\build\vectorscan-rs-sys-d4b542f12fe7422c\out\vectorscan-vectorscan-5.4.11
  Successfully applied patches to Vectorscan source directory at C:\Users\LeronGray\dev\vectorscan-rs\target\debug\build\vectorscan-rs-sys-d4b542f12fe7422c\out\vectorscan-vectorscan-5.4.11
  CMake Warning (dev) at cmake/boost.cmake:17 (find_package):
    Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
    variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.

    CMake variable BOOST_ROOT is set to:

      C:\Users\LeronGray\dev\boost_1_88_0

    For compatibility, find_package is ignoring the variable, but code in a
    .cmake module might still use it.
  Call Stack (most recent call first):
    CMakeLists.txt:27 (include)
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning (dev) at cmake/boost.cmake:17 (find_package):
    Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
    --help-policy CMP0167" for policy details.  Use the cmake_policy command to
    set the policy and suppress this warning.

  Call Stack (most recent call first):
    CMakeLists.txt:27 (include)
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
    Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
  Call Stack (most recent call first):
    C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
    C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/FindPkgConfig.cmake:114 (find_package_handle_standard_args)
    CMakeLists.txt:29 (find_package)


  thread 'main' panicked at C:\Users\LeronGray\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.54\src/lib.rs:1119:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
